### ISSUE TITLE
Crash when starting Mastalab

### ISSUE THREAD

**Issue by Aldarone** [stom79/mastalab#286]
I'm using the last beta version from the Play Store, I tried emptying the cache and kill Mastalab before starting it again but everytime I open it from the launcher it crashes.

```
01-28 13:36:57.563 22987 22987 E AndroidRuntime: FATAL EXCEPTION: main
01-28 13:36:57.563 22987 22987 E AndroidRuntime: Process: fr.gouv.etalab.mastodon, PID: 22987
01-28 13:36:57.563 22987 22987 E AndroidRuntime: java.lang.ClassCastException: fr.gouv.etalab.mastodon.drawers.StatusListAdapter$ViewHolderEmpty cannot be cast to fr.gouv.etalab.mastodon.drawers.StatusListAdapter$ViewHolder
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at fr.gouv.etalab.mastodon.drawers.StatusListAdapter.onViewAttachedToWindow(StatusListAdapter.java:222)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:6987)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:758)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8029)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7987)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7975)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1572)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:874)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:729)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-28 13:36:57.563 22987 22987 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
---

Android version: 7.1.2

**Comment by stom79** [comment]
Sorry. The fix should be available in few hours on the store or you can get it here: https://github.com/stom79/mastalab/releases/tag/1.7.8
