### ISSUE TITLE
Crash when sharing a .mp4 file

### ISSUE THREAD

**Issue by Aldarone** [stom79/mastalab#288]
Pictures and GIFs are ok but when I try to send an mp4 in a toot, Mastalab crashes : 

```
01-29 13:13:22.196 22038 22102 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
01-29 13:13:22.196 22038 22102 E AndroidRuntime: Process: fr.gouv.etalab.mastodon, PID: 22038
01-29 13:13:22.196 22038 22102 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
01-29 13:13:22.196 22038 22102 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getByteCount()' on a null object reference
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	at fr.gouv.etalab.mastodon.activities.TootActivity$asyncPicture.doInBackground(TootActivity.java:808)
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	at fr.gouv.etalab.mastodon.activities.TootActivity$asyncPicture.doInBackground(TootActivity.java:793)
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-29 13:13:22.196 22038 22102 E AndroidRuntime: 	... 3 more
```

Instance: https://ltch.fr/

Mastalab version: 1.7.8

Android version: 7.1.2

**Comment by stom79** [comment]
Thanks. It's fixed.

**Comment by Aldarone** [comment]
This morning I noticed that I was mistaken when I said that GIFs where ok. Apparently they get converted in PNG before being send.

**Comment by stom79** [comment]
Would you mind to test [this apk](https://github.com/stom79/mastalab/blob/bug_fix/app/playstore/release/app-playstore-release-fix-media.apk?raw=true)? Thanks.

**Comment by Aldarone** [comment]
It works 👍
