### ISSUE TITLE
Crash RuntimeException

### ISSUE THREAD

**Issue by yeKcim** [stom79/mastalab#67]
When I run mastalab, I've got sometimes :
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:318)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
at fr.gouv.etalab.mastodon.client.API.<init>(API.java:124)
at fr.gouv.etalab.mastodon.asynctasks.RetrieveNotificationsAsyncTask.doInBackground(RetrieveNotificationsAsyncTask.java:61)
at fr.gouv.etalab.mastodon.asynctasks.RetrieveNotificationsAsyncTask.doInBackground(RetrieveNotificationsAsyncTask.java:32)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
```
If I run again just after this crash, the error does not appear.

Mastalab 1.5.7

**Comment by stom79** [comment]
Unfortunately Fdroid is late with releases. [Current version](https://github.com/stom79/mastalab/releases) is 1.6.3
This crash has been fixed by adding a [control](https://github.com/stom79/mastalab/commit/fe29b83e2e6055141c58459e165f5ee7bd512b65#diff-b9b7700f9a0777f9bcc7ed79d153302c). That was done few time after the release 1.5.7.

**Comment by yeKcim** [comment]
⇒ #60

Thank you for your answer stom79
